### ISSUE TITLE
lxc-docker vs. docker-engine

### ISSUE THREAD

**Issue by ambsw-technology** [merll/docker-fabric#6]
Docker's [latest installation instructions](https://docs.docker.com/engine/installation/linux/ubuntulinux/) instruct users to install `docker-engine`.  This project sill references `lxc-docker`.  Is there a reason this project doesn't reflect the latest instructions?

**Comment by merll** [comment]
Thank you for the report! This will be updated in the next release.

**Comment by merll** [comment]
The installation tasks have been updated accordingly in ``0.3.10``.
